package ParameterSelection;

import Communications.Observer;
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dbennett3
 */
public class ParameterSelectionPanel extends javax.swing.JPanel implements Observer {

    private final static String[] tabNames = {"PILOT","GLIDER","AIRFIELD","DRUM"};
    
    public void SetCard(int index)
    {
        final CardLayout layout = (CardLayout)this.getLayout();
        layout.show(this, tabNames[index]);
    }

    public void clear()
    {
        pilotPanel.clear();
        sailplanePanel.clear();
        airfieldPanel.clear();
    }
    /**
     * Creates new form ParameterSelectionPanel
     */
    public ParameterSelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pilotPanel = new PilotPanel();
        sailplanePanel = new SailplanePanel();
        airfieldPanel = new AirfieldPanel();
        drumPanel = new DrumPanel();
        
        setLayout(new CardLayout(0, 0));

        this.add(tabNames[0], pilotPanel);

        this.add(tabNames[1], sailplanePanel);
        
        this.add(tabNames[2], airfieldPanel);
        
        this.add(tabNames[3], drumPanel);

        
    }// </editor-fold>//GEN-END:initComponents
    
    public void update(String s){};
    
    public void update()
    {
        pilotPanel.update();
        sailplanePanel.update();
        airfieldPanel.update("1");
        airfieldPanel.update("2");
        airfieldPanel.update("3");
        airfieldPanel.update("4");
        drumPanel.update();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PilotPanel pilotPanel;
    private SailplanePanel sailplanePanel;
    private AirfieldPanel airfieldPanel;
    private DrumPanel drumPanel;
    // End of variables declaration//GEN-END:variables
}
