package DashboardInterface;


import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;
import javax.imageio.ImageIO;

/**
 *
 * @author Matt Dargen
 */
public class StateMachinePanel extends javax.swing.JPanel {

    /**
     * Creates new form StateMachinePanel
     */
    
    JTextField last = new JTextField();
    
    public StateMachinePanel() {;
        initComponents();   
    }
    
    public void updateState(int state){
        
        stateLabel.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/DashboardInterface/images/" + stateIntToString(state) + ".png")));
        
    }
    
    public String stateIntToString(int state)
    {
        switch(state)
        {
            case 0:
                return "safe";
            case 1:
                return "prep";
            case 2:
                return "armed";
            case 3:
                return "profile";
            case 4:
                return "ramp";
            case 5:
                return "constant";
            case 6:
                return "recovery";
            case 7:
                return "retrieve";
            case 14:
                return "stop";
            case 15:
                return "abort";
            default:
                return "";
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stateLabel = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        stateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashboardInterface/images/safe.png"))); // NOI18N

        jToggleButton1.setText("random");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        
        this.setBackground(Color.WHITE);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    
    }//GEN-LAST:event_formKeyPressed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        //updateState(getRandomState());
    }//GEN-LAST:event_jToggleButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
